### ISSUE TITLE
 58 Forrest St Cottesloe

### ISSUE THREAD

**Issue by samwilson** [samwilson/cfb#1]
See http://www.inherit.stateheritage.wa.gov.au/Public/Inventory/Details/4dd4ebca-c6da-4c83-8bbf-35c4f5f89a50

> The land was purchased in 1933 from Judge Ackland's estate [he drowned in a boating accident] by Ralph and Vera Munday who lived next door in "Oceania". They built four flats. These flats were owned by Mrs T.G. Molloy who sold to the current owner Mrs Africh.

**Comment by juliad-b** [comment]
Leave it for now.
