### ISSUE TITLE
John Darcy Barker birth & death certificates

### ISSUE THREAD

**Issue by samwilson** [samwilson/cfb#187]
FreeBMD Births Mar 1912: Barker, John D. Mother: Whitehead. Wirral, vol.~ 8a, p.~837.

http://www.freebmd.org.uk/cgi/information.pl?cite=8Cec9%2BQK2Ye81TmNPozDYA&scan=1

**Comment by samwilson** [comment]
This might be his death record:
http://www.freebmd.org.uk/cgi/information.pl?cite=RfWBM2vossd5UkmcWbJN3A&scan=1

**Comment by samwilson** [comment]
```
Deaths  Sep  1962
--
BARKER | John D. | 50 | Wirral | 10a | 641

```

**Comment by Rms125** [comment]
Hi Sam how you doing

**Comment by samwilson** [comment]
@Rms125 Hi, do you have a question or info about John Darcy Barker?

**Comment by Rms125** [comment]
Not that I care to share

**Comment by Rms125** [comment]
Sent from my iPhone

**Comment by samwilson** [comment]
Details moved to https://archives.org.au/John_Darcy_Barker
